<?php
/**
 * Download Tracker plugin for Craft CMS 4.x & 5.x
 *
 * @link      https://coysh.digital
 * @copyright Copyright (c) Coysh Digital
 */

namespace coyshdigital\downloadtracker\helpers;

/**
 * Distils third-party crawler lists into a compact set of extra User-Agent
 * substring tokens, keeping only the ones that add coverage beyond the built-in
 * detection.
 *
 * Three community sources are understood:
 *  - Kikobeats/top-crawler-agents      (JSON array of sample User-Agents)
 *  - monperrus/crawler-user-agents     (JSON array of {pattern, ...})
 *  - matomo-org/device-detector bots   (YAML fixtures with user_agent: lines)
 *
 * The output is deliberately small. The plugin already treats any User-Agent
 * containing bot/crawl/spider/slurp/monitor/preview/headless as a crawler, and
 * knows the well-known crawlers by name, so every token those already catch is
 * dropped here. What's left is the "silent" crawlers - the ones that identify
 * themselves but carry none of those give-away words (yeti, ia_archiver,
 * barkrowler, mediapartners, apis-google, duckduckgo, nutch, and the like).
 *
 * This helper is pure - no Craft, no I/O - so the shipped baseline list can be
 * generated by running it over the raw sources from the command line, and the
 * in-CP refresh produces byte-for-byte the same result from the same inputs.
 *
 * @author Coysh Digital
 * @since 1.5.0
 */
final class CrawlerTokens
{
    // Constants
    // =========================================================================

    /**
     * @var int Shortest token kept. Below this a substring match is too likely
     * to fire on an unrelated User-Agent.
     */
    public const MIN_LENGTH = 5;

    /**
     * @var int Longest token kept. A whole example User-Agent isn't a token;
     * anything this long is extraction gone wrong, so drop it.
     */
    public const MAX_LENGTH = 40;

    /**
     * @var string[] Substrings that appear in ordinary browser User-Agents.
     * A candidate containing any of these is never a safe crawler token - it
     * would match real people - so it's discarded whatever else it looks like.
     */
    private const BROWSER_DENYLIST = [
        'mozilla', 'applewebkit', 'khtml', 'gecko', 'chrome', 'safari',
        'version', 'mobile', 'windows', 'macintosh', 'android', 'linux',
        'x11', 'compatible', 'iphone', 'ipad', 'like mac', 'intel', 'trident',
        'edge', 'edg/', 'opr/', 'opera', 'firefox', 'samsungbrowser', 'crios',
        'fxios', 'webkit', 'build/', 'wow64', 'win64', 'cpu os', 'cros',
    ];

    /**
     * @var string[] Tokens dropped by exact match. Two kinds: brands whose apps
     * embed a browser that real people browse from (so their User-Agent belongs
     * to a person, not a crawler), and plain English words broad enough to fire
     * on an unrelated User-Agent. Matched exactly, so distinctive compounds that
     * merely contain one of these - google-read-aloud, sparkpost, character-ai -
     * are untouched.
     */
    private const RISKY_EXACT = [
        // Brands with in-app browsers or phone User-Agents = real people
        'amazon', 'facebook', 'google', 'browser', 'desktop', 'spotify',
        'viber', 'yahoo', 'docomo', 'samsung-sgh-e250', 'instagram', 'snapchat',
        // Plain words too generic to match blindly as substrings
        'download', 'security', 'scanning', 'library', 'image', 'content',
        'network', 'server', 'services', 'machine', 'parser', 'fetch', 'search',
        'report', 'research', 'measure', 'metadata', 'domain', 'domains',
        'favicon', 'online', 'email', 'agent', 'cloud', 'current', 'better',
        'crazy', 'hello', 'support', 'optimize', 'visitor', 'observer',
        'explorer', 'checker', 'tester', 'verifier', 'encrypt', 'readable',
        'scripting', 'character', 'electronic', 'summers', 'jesus', 'james',
        'laude', 'known', 'willow', 'potions', 'valve', 'spark', 'fluid',
        'capsule', 'critical', 'friendly', 'sonic', 'ninja', 'nitro', 'desktop',
        'mobile', 'quora', 'https', 'paypal', 'notion',
    ];

    // Public Methods
    // =========================================================================

    /**
     * Distils the three raw sources into a sorted, deduplicated token list.
     *
     * Any source string may be empty - a source that failed to download is
     * simply skipped, and the others still contribute.
     *
     * @param string $kikobeatsJson Raw index.json contents.
     * @param string $monperrusJson Raw crawler-user-agents.json contents.
     * @param string $matomoYaml Raw bots.yml contents.
     * @return string[] Lower-case tokens, sorted, unique.
     */
    public static function distil(string $kikobeatsJson, string $monperrusJson, string $matomoYaml): array
    {
        $tokens = [];

        // monperrus ships short, near-literal regex patterns: the longest literal
        // run of the pattern is the crawler's name.
        foreach (self::_monperrusPatterns($monperrusJson) as $pattern) {
            $token = self::_clean((string)self::_longestIsland(strtolower(trim($pattern))));

            if ($token !== null) {
                $tokens[$token] = true;
            }
        }

        // The other two ship whole example User-Agents. Their reliable signal is
        // the id inside "compatible; X" or the leading identifier - never the
        // longest run, which on a full User-Agent is a version number or a URL.
        foreach (array_merge(self::_jsonStrings($kikobeatsJson), self::_matomoUserAgents($matomoYaml)) as $ua) {
            $token = self::_tokenFromUserAgent((string)$ua);

            if ($token !== null) {
                $tokens[$token] = true;
            }
        }

        $tokens = array_keys($tokens);
        sort($tokens);

        return $tokens;
    }

    /**
     * Serialises a token list to the on-disk format: one token per line, with a
     * couple of comment lines carrying the generation date and count. Comment
     * lines start with `#` and are ignored on read.
     *
     * @param string[] $tokens
     * @return string
     */
    public static function toFile(array $tokens): string
    {
        $header = [
            '# Download Tracker - distilled crawler tokens.',
            '# Generated ' . gmdate('Y-m-d\TH:i:s\Z') . ' - ' . count($tokens) . ' tokens.',
            '# One User-Agent substring per line; lines starting with # are ignored.',
        ];

        return implode("\n", array_merge($header, $tokens)) . "\n";
    }

    /**
     * Reads a token list back from the on-disk format.
     *
     * @param string $contents
     * @return string[]
     */
    public static function fromFile(string $contents): array
    {
        $tokens = [];

        foreach (preg_split('/\R/', $contents) ?: [] as $line) {
            $line = trim($line);

            if ($line !== '' && $line[0] !== '#') {
                $tokens[] = $line;
            }
        }

        return $tokens;
    }

    // Private Methods
    // =========================================================================

    /**
     * Extracts a clean crawler token from a whole example User-Agent, or null.
     * Uses only the leading id and the "compatible; X" id - strategies that
     * target the crawler's name rather than a version string buried in the UA.
     *
     * @param string $raw
     * @return string|null
     */
    private static function _tokenFromUserAgent(string $raw): ?string
    {
        $raw = strtolower(trim($raw));
        $raw = trim($raw, "'\" \t");

        if ($raw === '') {
            return null;
        }

        foreach ([self::_compatibleId($raw), self::_leadingId($raw)] as $candidate) {
            $token = self::_clean((string)$candidate);

            if ($token !== null) {
                return $token;
            }
        }

        return null;
    }

    /**
     * Pulls the crawler id out of a "Mozilla/5.0 (compatible; Name/1.0; +url)"
     * shaped User-Agent.
     *
     * @param string $raw
     * @return string|null
     */
    private static function _compatibleId(string $raw): ?string
    {
        if (preg_match('/compatible;\s*([a-z0-9][a-z0-9._+\- ]{2,})/', $raw, $m)) {
            return $m[1];
        }

        return null;
    }

    /**
     * Pulls the leading identifier from a "Name/1.0 (…)" shaped string. Skips
     * anything that starts as a browser User-Agent, which carries no id here.
     *
     * @param string $raw
     * @return string|null
     */
    private static function _leadingId(string $raw): ?string
    {
        if (str_starts_with($raw, 'mozilla')) {
            return null;
        }

        if (preg_match('/^[a-z0-9][a-z0-9._+\-]{2,}/', $raw, $m)) {
            return $m[0];
        }

        return null;
    }

    /**
     * Returns the longest literal run from a (de-escaped) regex pattern.
     *
     * @param string $raw
     * @return string|null
     */
    private static function _longestIsland(string $raw): ?string
    {
        $deEscaped = str_replace('\\', '', $raw);

        if (!preg_match_all('/[a-z0-9._+\-]{4,}/', $deEscaped, $m)) {
            return null;
        }

        $longest = '';
        foreach ($m[0] as $run) {
            if (strlen($run) > strlen($longest)) {
                $longest = $run;
            }
        }

        return $longest !== '' ? $longest : null;
    }

    /**
     * Normalises a candidate id to its core token and applies every filter,
     * returning the token to keep or null to drop it.
     *
     * @param string $candidate
     * @return string|null
     */
    private static function _clean(string $candidate): ?string
    {
        $candidate = trim($candidate);

        // Version and path noise: keep only up to the first slash, then trim
        // punctuation off the ends.
        $candidate = explode('/', $candidate)[0];
        $candidate = trim($candidate, " \t.-_+");

        // A token with an internal space is a phrase, not a substring we want to
        // match blindly; the built-in list already carries the few worth having.
        if ($candidate === '' || str_contains($candidate, ' ')) {
            return null;
        }

        $length = strlen($candidate);

        if ($length < self::MIN_LENGTH || $length > self::MAX_LENGTH) {
            return null;
        }

        // Must read as a name: start with a letter, and be mostly letters. This
        // drops version numbers, timestamps, hashes and kernel strings, which is
        // most of what the raw sources carry besides the crawler names.
        if (!preg_match('/^[a-z]/', $candidate)) {
            return null;
        }

        if (preg_match('/\d+\.\d/', $candidate)) {
            return null;
        }

        if (preg_match_all('/[a-z]/', $candidate) < 4) {
            return null;
        }

        // Two or more dots is a multi-label hostname (someone's personal bot
        // domain), not a stable crawler token.
        if (substr_count($candidate, '.') >= 2) {
            return null;
        }

        if (in_array($candidate, self::RISKY_EXACT, true)) {
            return null;
        }

        foreach (self::BROWSER_DENYLIST as $bad) {
            if (str_contains($candidate, $bad)) {
                return null;
            }
        }

        // Already caught by the built-in generic pattern or a named crawler, so
        // adding it would only grow the list without widening coverage.
        if (RequestSignals::alreadyDetected($candidate)) {
            return null;
        }

        return $candidate;
    }

    /**
     * Reads the `pattern` field from each entry of the monperrus JSON.
     *
     * @param string $json
     * @return string[]
     */
    private static function _monperrusPatterns(string $json): array
    {
        $data = self::_decodeArray($json);
        $patterns = [];

        foreach ($data as $entry) {
            if (is_array($entry) && isset($entry['pattern']) && is_string($entry['pattern'])) {
                $patterns[] = $entry['pattern'];
            }
        }

        return $patterns;
    }

    /**
     * Reads a flat JSON array of strings (the Kikobeats format).
     *
     * @param string $json
     * @return string[]
     */
    private static function _jsonStrings(string $json): array
    {
        $strings = [];

        foreach (self::_decodeArray($json) as $entry) {
            if (is_string($entry)) {
                $strings[] = $entry;
            }
        }

        return $strings;
    }

    /**
     * Reads the `user_agent:` values from the matomo bots fixture, without a
     * YAML parser - only that one field is needed.
     *
     * @param string $yaml
     * @return string[]
     */
    private static function _matomoUserAgents(string $yaml): array
    {
        if ($yaml === '' || !preg_match_all('/^\s*user_agent:\s*(.+?)\s*$/m', $yaml, $m)) {
            return [];
        }

        return $m[1];
    }

    /**
     * Decodes a JSON string to an array, or an empty array on any failure.
     *
     * @param string $json
     * @return array<int, mixed>
     */
    private static function _decodeArray(string $json): array
    {
        if ($json === '') {
            return [];
        }

        $data = json_decode($json, true);

        return is_array($data) ? $data : [];
    }
}
